import { minifySync } from 'oxc-minify';
import { defineConfig } from 'vite-plus';

const entry = ['src/index.ts', 'src/core.ts', 'src/signals.ts', 'src/map.ts', 'src/symbols.ts'];

/**
 * Mangles internal `_`-prefixed properties to short names in the production build. A cache shared
 * across chunks keeps the names consistent between `core.js`, `signals.js` and `map.js`. Identifier
 * mangling, compression and whitespace removal are left to the consumer's bundler.
 */
function mangleProps() {
  const cache: Record<string, string | false> = {};
  return {
    name: 'mangle-props',
    renderChunk(code: string, chunk: { fileName: string }) {
      const result = minifySync(chunk.fileName, code, {
        module: true,
        compress: false,
        mangle: false,
        codegen: { removeWhitespace: false },
        mangleProps: { include: /^_/, cache },
      });
      if (result.errors.length) throw new Error(result.errors.map((e) => e.message).join('\n'));
      if (result.mangleCache) Object.assign(cache, result.mangleCache);
      return { code: result.code, map: result.map ?? null };
    },
  };
}

/** Shared `vp pack` (tsdown) options for both outputs. Types are emitted separately by `tsc`. */
const pack = {
  entry,
  format: 'esm',
  platform: 'neutral',
  target: 'esnext',
  tsconfig: 'tsconfig.build.json',
  clean: true,
  dts: false,
} as const;

export default defineConfig({
  define: {
    __DEV__: 'true',
    __TEST__: 'true',
  },
  test: {
    globals: true,
    // Required by `tests/gc.test.ts` so `global.gc` is available inside the worker.
    execArgv: ['--expose-gc'],
    benchmark: {
      include: ['bench/**/*.bench.js'],
    },
  },
  pack: [
    // Development build: readable, with dev-only diagnostics and debugging ids.
    {
      ...pack,
      outDir: 'dist/dev',
      define: { __DEV__: 'true', __TEST__: 'false' },
    },
    // Production build: internal `_`-prefixed properties are mangled to short names.
    {
      ...pack,
      outDir: 'dist/prod',
      define: { __DEV__: 'false', __TEST__: 'false' },
      plugins: [mangleProps()],
    },
  ],
  fmt: {
    useTabs: false,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
    tabWidth: 2,
    sortPackageJson: false,
    // CHANGELOG.md is generated by standard-version.
    ignorePatterns: ['CHANGELOG.md', 'dist', 'bench/.baseline'],
  },
  lint: {
    plugins: ['typescript', 'unicorn', 'oxc'],
    categories: { correctness: 'error' },
    rules: {
      // `new Array(n)` is deliberate pre-allocation in src/map.ts and the benchmarks.
      'unicorn/no-new-array': 'off',
    },
    env: { builtin: true },
    ignorePatterns: ['dist', 'bench/.baseline'],
    overrides: [
      {
        // Vendored / legacy benchmark code.
        files: ['bench/layers.js', 'bench/solid-js-baseline.js'],
        rules: { 'no-unused-vars': 'off', 'no-unused-expressions': 'off' },
      },
    ],
  },
});
